### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by LiorRabin** [argentlabs/argent-contracts#66]
Hi,
I'm trying to run `npm compile` on the `develop` branch and getting the following errors:

```
 Compilation warnings encountered:

/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:36:31: Warning: This declaration shadows an existing declaration.
    function isApprovedForAll(address owner, address operator) external view returns (bool);
                              ^-----------^
/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:32:5: The shadowed declaration is here:
    function owner(bytes32 node) external view returns (address);
    ^-----------------------------------------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:142:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            wallet := create2(0, add(code, 0x20), mload(code), newsalt)
                      ^-----------------------------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:175:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            wallet := create2(0, add(code, 0x20), mload(code), newsalt)
                      ^-----------------------------------------------^


{ Error: /Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:36:31: Warning: This declaration shadows an existing declaration.
    function isApprovedForAll(address owner, address operator) external view returns (bool);
                              ^-----------^
/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:32:5: The shadowed declaration is here:
    function owner(bytes32 node) external view returns (address);
    ^-----------------------------------------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/CommunityManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.
    BaseModule(_registry, NAME)
    ^-------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/WalletOwnershipManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.
    BaseModule(_registry, NAME)
    ^-------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:142:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            wallet := create2(0, add(code, 0x20), mload(code), newsalt)
                      ^-----------------------------------------------^
,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:175:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            wallet := create2(0, add(code, 0x20), mload(code), newsalt)
                      ^-----------------------------------------------^
    at new ExtendableError (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-error/index.js:7:19)
    at new CompileError (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-compile/compile-error.js:11:5)
    at Promise (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-compile/index.js:81:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   '/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:36:31: Warning: This declaration shadows an existing declaration.\n    function isApprovedForAll(address owner, address operator) external view returns (bool);\n                              ^-----------^\n/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:32:5: The shadowed declaration is here:\n    function owner(bytes32 node) external view returns (address);\n    ^-----------------------------------------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/CommunityManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.\n    BaseModule(_registry, NAME)\n    ^-------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/WalletOwnershipManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.\n    BaseModule(_registry, NAME)\n    ^-------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:142:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.\n            wallet := create2(0, add(code, 0x20), mload(code), newsalt)\n                      ^-----------------------------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:175:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.\n            wallet := create2(0, add(code, 0x20), mload(code), newsalt)\n                      ^-----------------------------------------------^\n\u001b[31mCompilation failed. See above.\u001b[39m',
  stack:
   'Error: /Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:36:31: Warning: This declaration shadows an existing declaration.\n    function isApprovedForAll(address owner, address operator) external view returns (bool);\n                              ^-----------^\n/Users/liorrabin/Dev/fuse/argent-contracts/lib/ens/ENS.sol:32:5: The shadowed declaration is here:\n    function owner(bytes32 node) external view returns (address);\n    ^-----------------------------------------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/CommunityManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.\n    BaseModule(_registry, NAME)\n    ^-------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/modules/WalletOwnershipManager.sol:13:5: TypeError: Wrong argument count for modifier invocation: 2 arguments given but expected 3.\n    BaseModule(_registry, NAME)\n    ^-------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:142:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.\n            wallet := create2(0, add(code, 0x20), mload(code), newsalt)\n                      ^-----------------------------------------------^\n,/Users/liorrabin/Dev/fuse/argent-contracts/contracts/wallet/WalletFactory.sol:175:23: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.\n            wallet := create2(0, add(code, 0x20), mload(code), newsalt)\n                      ^-----------------------------------------------^\n    at new ExtendableError (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-error/index.js:7:19)\n    at new CompileError (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-compile/compile-error.js:11:5)\n    at Promise (/Users/liorrabin/Dev/fuse/argent-contracts/node_modules/etherlime/cli-commands/compiler/etherlime-compile/index.js:81:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  name: 'CompileError' }
```

**Comment by elenadimitrova** [comment]
The project compiles successfully. See [latest Circle build ](https://circleci.com/gh/argentlabs/argent-contracts/199)
But perhaps you have not compiled the library contract dependencies via `npm run compile:lib` see Readme.

**Comment by LiorRabin** [comment]
It was a problem on one of our contracts which I missed in the output log, so all good. Thanks for the response.
